### ISSUE TITLE
Webpack does not bundle

### ISSUE THREAD

**Issue by HansS** [MoonHighway/react-bulletin-board#1]
windows 10

> node -v && npm -v
> v5.10.0
> 3.7.1

Hans@HP-HANS C:\Users\Hans\Web\bootcamps\galvanize\react-sticky-notes

> webpack
> Hash: efea76b1048c3a97b963
> Version: webpack 1.13.0
> Time: 797ms
>     + 1 hidden modules

ERROR in ./app-client.js
Module build failed: ReferenceError: [BABEL] C:\Users\Hans\Web\bootcamps\galvanize\react-sticky-notes\app-client.js: Unknown option: C:\Users\Hans.babelrc.presets
    at Logger.error (C:\Users\Hans\Web\bootcamps\galvanize\react-sticky-notes\node_modules\babel-core\lib\transformation\file\logger.js:58:11)
    at OptionManager.mergeOptions (C:\Users\Hans\Web\bootcamps\galvanize\react-sticky-notes\node_modules\babel-core\lib\transformation\file\options\option-manager.js:126:29)
    at OptionManager.addConfig (C:\Users\Hans\Web\bootcamps\galvanize\react-sticky-notes\node_modules\babel-core\lib\transformation\file\options\option-manager.js:107:10)

```
at OptionManager.findConfigs (C:\Users\Hans\Web\bootcamps\galvanize\react-sticky-notes\node_modules\babel-core\lib\transformation\file\options\option-manager.js:168:35)
at OptionManager.init (C:\Users\Hans\Web\bootcamps\galvanize\react-sticky-notes\node_modules\babel-core\lib\transformation\file\options\option-manager.js:229:12)
at File.initOptions (C:\Users\Hans\Web\bootcamps\galvanize\react-sticky-notes\node_modules\babel-core\lib\transformation\file\index.js:147:75)
at new File (C:\Users\Hans\Web\bootcamps\galvanize\react-sticky-notes\node_modules\babel-core\lib\transformation\file\index.js:137:22)
at Pipeline.transform (C:\Users\Hans\Web\bootcamps\galvanize\react-sticky-notes\node_modules\babel-core\lib\transformation\pipeline.js:164:16)
at transpile (C:\Users\Hans\Web\bootcamps\galvanize\react-sticky-notes\node_modules\babel-loader\index.js:12:22)
at Object.module.exports (C:\Users\Hans\Web\bootcamps\galvanize\react-sticky-notes\node_modules\babel-loader\index.js:71:12)
```

**Comment by eveporcello** [comment]
This code was written a year-ish ago, and a lot has changed in React and the ecosystem.

When I get a moment, I will:
1. Update Babel to version 6
2. Add appropriate babel-loaders to the webpack.config. (https://babeljs.io/docs/setup/#installation)
3. Add babelrc to load ES2015 and React
4. Update package.json

I'll get to that sometime soon and will close the issue when I do. If that takes too long for your purposes, you can always submit a pull request :)
